//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace integrating.web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admins
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Pwd { get; set; }
        public System.DateTime AddTime { get; set; }
        public System.DateTime EditTime { get; set; }
        public bool State { get; set; }
    }
}
