//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace integrating.web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class audit
    {
        public int Id { get; set; }
        public string business_id { get; set; }
        public string audit_user { get; set; }
        public string audit_datetime { get; set; }
        public string audit_opinion { get; set; }
        public string audit_type { get; set; }
        public System.DateTime date { get; set; }
    }
}
