//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace integrating.web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class business
    {
        public int Id { get; set; }
        public string app_User { get; set; }
        public System.DateTime app_datetime { get; set; }
        public string type { get; set; }
        public string score { get; set; }
        public string score_item { get; set; }
        public string state { get; set; }
        public System.DateTime updatetime { get; set; }
        public string userId { get; set; }
        public string beizhu { get; set; }
        public bool isUsed { get; set; }
        public string unscore { get; set; }
    }
}
