//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace integrating.web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DD_User
    {
        public string userid { get; set; }
        public string unionid { get; set; }
        public string order { get; set; }
        public string isAdmin { get; set; }
        public string isBoss { get; set; }
        public string isHide { get; set; }
        public string isLeader { get; set; }
        public string name { get; set; }
        public string active { get; set; }
        public string deptID { get; set; }
        public string position { get; set; }
        public string avatar { get; set; }
        public string jobnumber { get; set; }
        public int id_prikey1 { get; set; }
    }
}
