//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace integrating.web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JFitem
    {
        public int Id { get; set; }
        public string JF_serial { get; set; }
        public string JF_name { get; set; }
        public string score { get; set; }
        public string desp { get; set; }
        public string par_Id { get; set; }
        public string unscore { get; set; }
        public string ismul { get; set; }
        public string exitmultp { get; set; }
    }
}
