//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace integrating.web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mms_ZEmployee
    {
        public int ZEmployee_ID { get; set; }
        public string ZEmployee_Num { get; set; }
        public string ZEmployee_Name { get; set; }
        public string ZEmployee_Organization { get; set; }
        public string ZEmployee_Department { get; set; }
        public string ZEmployee_Status { get; set; }
        public string ZEmployee_Sex { get; set; }
        public Nullable<System.DateTime> ZEmployee_Birthday { get; set; }
        public string ZEmployee_JiGuan { get; set; }
        public string ZEmployee_MingZhu { get; set; }
        public string ZEmployee_DiYiXueLi { get; set; }
        public string ZEmployee_DiYiXueWei { get; set; }
        public string ZEmployee_DiYiXueXiao { get; set; }
        public string ZEmployee_ZhuiGaoXueLi { get; set; }
        public string ZEmployee_BestSchool { get; set; }
        public string ZEmployee_BestZhuanYe { get; set; }
        public string ZEmployee_HealthStatus { get; set; }
        public string ZEmployee_HunYingZhuangKuang { get; set; }
        public string ZEmployee_PeiOuXingMing { get; set; }
        public string ZEmployee_PeiOuGongZhuoDanWei { get; set; }
        public string ZEmployee_PeiOuDianHua { get; set; }
        public string ZEmployee_CardType { get; set; }
        public string ZEmployee_CardNum { get; set; }
        public string ZEmployee_HuJi { get; set; }
        public string ZEmployee_OldName { get; set; }
        public string ZEmployee_JoinWorkDate { get; set; }
        public string ZEmployee_JoinBankDate { get; set; }
        public string ZEmployee_ZiNvXingMing { get; set; }
        public string ZEmployee_SheBaoZhangHao { get; set; }
        public string ZEmployee_ShiFouShiYongRenYuan { get; set; }
        public string ZEmployee_Phone { get; set; }
        public string ZEmployee_GDPhone { get; set; }
        public string ZEmployee_Adress { get; set; }
        public Nullable<System.DateTime> ZEmployee_CancelDate { get; set; }
        public string ZEmployee_Type { get; set; }
        public string ZEmployee_GeRenAiHao { get; set; }
        public string ZEmployee_ZiNvZhuangKuang { get; set; }
        public string ZEmployee_Memo2 { get; set; }
        public string ZEmployee_GongZhuoGangWei { get; set; }
        public string ZEmployee_XingZhengZhiWu { get; set; }
        public string ZEmployee_RengZhiShiJian { get; set; }
        public string ZEmployee_ChuShengDi { get; set; }
        public string ZEmployee_Memo7 { get; set; }
        public string ZEmployee_RengGangShiJian { get; set; }
        public string ZEmployee_ZhiChengLeiBie { get; set; }
        public string ZEmployee_ZhiChengJiBie { get; set; }
        public string ZEmployee_OrganizationNum { get; set; }
        public string ZEmployee_ZhuiGaoXueLiXueXiao { get; set; }
        public string ZEmployee_ZhuiGaoXueLiZhuanYe { get; set; }
        public string ZEmployee_ZhongFengLei { get; set; }
        public string ZEmployee_HeTongLeiXing { get; set; }
        public string ZEmployee_ShiFouLianSheShengPi { get; set; }
        public string ZEmployee_ZhengZhiMianMao { get; set; }
        public string ZEmployee_YingHangCongYeZiGeZhengKeMu { get; set; }
        public string ZEmployee_LiCaiGuiHuaShi { get; set; }
        public string ZEmployee_XiaoHao { get; set; }
        public string ZEmployee_RuDangShiJian { get; set; }
        public string ZEmployee_ZhengQuanChongYeZhiGe { get; set; }
        public string ZEmployee_QiTaChongYeZiGe { get; set; }
        public string ZEmployee_ZiNvGeShu { get; set; }
        public string ZEmployee_RenYuanXingZhengLeiXing { get; set; }
        public string ZEmployee_NianDuKaoHeDeFeng { get; set; }
        public string ZEmployee_XueXiJingLi { get; set; }
        public string ZEmployee_GongZhuoJingLi { get; set; }
        public string ZEmployee_JangChengXingXi { get; set; }
        public string ZEmployee_ChiYouGuJing { get; set; }
        public string ZEmployee_TiaoDang { get; set; }
        public string ZEmployee_ZhuGang { get; set; }
        public string ZEmployee_JianGang { get; set; }
        public string ZEmployee_GuiYuanNum { get; set; }
        public string ZEmployee_Memo32 { get; set; }
        public string ZEmployee_Memo33 { get; set; }
        public string ZEmployee_Memo34 { get; set; }
        public string ZEmployee_Memo35 { get; set; }
        public string ZEmployee_Memo36 { get; set; }
        public string ZEmployee_Memo37 { get; set; }
        public string ZEmployee_Memo38 { get; set; }
        public string ZEmployee_Memo39 { get; set; }
        public string ZEmployee_Memo40 { get; set; }
        public string ZEmployee_Memo41 { get; set; }
        public string ZEmployee_Memo42 { get; set; }
        public string ZEmployee_Memo43 { get; set; }
        public string ZEmployee_Memo44 { get; set; }
        public string ZEmployee_Memo45 { get; set; }
    }
}
