//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace integrating.web.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IntegratingEntities : DbContext
    {
        public IntegratingEntities()
            : base("name=IntegratingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admins> Admins { get; set; }
        public virtual DbSet<Article> ArticleSet { get; set; }
        public virtual DbSet<Menu> MenuSet { get; set; }
        public virtual DbSet<Button> ButtonSet { get; set; }
        public virtual DbSet<Role> RoleSet { get; set; }
        public virtual DbSet<Users> UsersSet { get; set; }
        public virtual DbSet<DD_Dept> DD_DeptSet { get; set; }
        public virtual DbSet<DD_User> DD_UserSet { get; set; }
        public virtual DbSet<business> businessSet { get; set; }
        public virtual DbSet<audit> auditSet { get; set; }
        public virtual DbSet<dic_date> dic_dateSet { get; set; }
        public virtual DbSet<Day_statistics> Day_statisticsSet { get; set; }
        public virtual DbSet<IntegratingSet> IntegratingSet { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<JFitem> JFitem { get; set; }
        public virtual DbSet<BussHistory> BussHistorySet { get; set; }
        public virtual DbSet<mms_ZEmployee> mms_ZEmployee { get; set; }
        public virtual DbSet<Role_Menu> Role_Menu { get; set; }
    }
}
